pipeline {
    agent any

    environment {
        CLICKHOUSE_JDBC_JAR = 'clickhouse-jdbc-all.jar'
        CLICKHOUSE_JDBC_VERSION = '0.6.0'
        HTTPCLIENT_JAR = 'httpclient5-5.1.3.jar'
        HTTPCORE_JAR = 'httpcore5-5.1.3.jar'
    }

    stages {
        stage('Start Services') {
            steps {
                sh 'docker-compose start || docker-compose up -d'
                sh 'sleep 15'
            }
        }

        stage('Init MySQL') {
            steps {
                sh 'docker exec mysql_to_clickhouse-mysql-1 sh -c "mysql -uroot -proot bank < /sql/init_mysql.sql" || true'
            }
        }

        stage('Register Debezium Connector') {
            steps {
                sh '''
                echo 'Registering Debezium Connector...'
                curl -i -X POST http://localhost:8083/connectors \
                  -H "Content-Type: application/json" \
                  --data-binary @debezium-connector.json || true
                '''
            }
        }

        stage('Prepare JARs') {
            steps {
                sh '''
                # Загрузка ClickHouse JDBC JAR
                if [ ! -f "$CLICKHOUSE_JDBC_JAR" ]; then
                  echo "Downloading ClickHouse JDBC driver..."
                  wget https://repo1.maven.org/maven2/com/clickhouse/clickhouse-jdbc/${CLICKHOUSE_JDBC_VERSION}/clickhouse-jdbc-${CLICKHOUSE_JDBC_VERSION}-all.jar \
                    -O $CLICKHOUSE_JDBC_JAR || { echo "Failed to download ClickHouse JDBC driver"; exit 1; }
                fi

                # Загрузка Apache HttpClient и HttpCore, если нужно
                if [ ! -f "$HTTPCLIENT_JAR" ]; then
                  wget https://repo1.maven.org/maven2/org/apache/httpcomponents/client5/httpclient5/5.1.3/httpclient5-5.1.3.jar \
                    -O $HTTPCLIENT_JAR || { echo "Failed to download HttpClient"; exit 1; }
                fi

                if [ ! -f "$HTTPCORE_JAR" ]; then
                  wget https://repo1.maven.org/maven2/org/apache/httpcomponents/core5/httpcore5/5.1.3/httpcore5-5.1.3.jar \
                    -O $HTTPCORE_JAR || { echo "Failed to download HttpCore"; exit 1; }
                fi
                '''
            }
        }

        stage('Create ClickHouse Views') {
            steps {
                sh '''
                docker exec clickhouse-server clickhouse-client \
                  --user=custom_user --password=0000 \
                  --query="CREATE DATABASE IF NOT EXISTS default;"
                '''
            }
        }

        stage('Run Spark Job') {
            steps {
                sh '''
                /opt/homebrew/bin/spark-submit \
                --jars clickhouse-jdbc-all.jar,httpclient5-5.1.3.jar,httpcore5-5.1.3.jar,\
                jars/spark-sql-kafka-0-10_2.12-3.5.0.jar,jars/kafka-clients-2.8.0.jar \
                etl/kafka_to_clickhouse.py
                '''
            }
        }
    }
}
